version: "3.8"

services:
  fastapi:
    image: ghcr.io/etalab-ia/albert-api/app:latest
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    environment:
      - CONFIG_FILE=/home/albert/conf/config.yml
    ports:
      - 8000:8000
    volumes:
     - .:/home/albert/conf # a config.yml file should be in this folder
     - ./app:/home/albert/app

  streamlit:
    image: ghcr.io/etalab-ia/albert-api/ui:latest
    command: ["streamlit", "run", "chat.py", "--server.port=8501", "--browser.gatherUsageStats", "false", "--theme.base", "light", "--server.maxUploadSize=10"]
    restart: always
    environment:
      - BASE_URL=http://fastapi:8000/v1
    ports:
      - 8501:8501

  qdrant:
    image: qdrant/qdrant:v1.9.7-unprivileged
    restart: always
    environment:
      - QDRANT__SERVICE__API_KEY=changeme
    ports: 
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant:/qdrant/storage

  redis:
    image: redis/redis-stack-server:7.2.0-v11
    restart: always
    environment:
      REDIS_ARGS: --dir /data --requirepass changeme --user username on >password ~* allcommands --save 60 1 --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    healthcheck:
        test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        interval: 4s
        timeout: 10s
        retries: 5

volumes:
  qdrant:
  redis:
