[project]
name = "albert-api"
version = "1.0.0"
description = "Albert API projects"
requires-python = ">=3.12"
license = { text = "MIT" }
dependencies = [
    "openai==1.43.0",
    "requests==2.32.3",
]

[project.optional-dependencies]
ui = [
    "streamlit==1.39.0",
    "streamlit-extras==0.5.0", 
]
app = [
    "langchain==0.2.15",
    "qdrant-client==1.10.1",
    "redis==5.0.7",
    "uvicorn==0.30.1",
    "fastapi==0.111.0",
    "prometheus-fastapi-instrumentator==7.0.0",
    "pyyaml==6.0.1",
    "python-magic==0.4.27",
    "grist-api==0.1.0",
    "pdfminer.six==20240706",
    "beautifulsoup4==4.12.3",
    "duckduckgo-search==6.2.13",
    "numpy==1.26.4",
    "slowapi==0.1.9",
    "six==1.16.0",
]
dev = [
    "ruff==0.6.5",
    "pre-commit==3.6.2",
    "jupyter==1.1.1", # to develop tutorials notebooks
]
test = [
    "pytest==8.3.3",
]

[tool.setuptools]
py-modules = []

[tool.ruff]
line-length = 150

[tool.ruff.lint]
ignore = ["F403", "F841"] # import * and never used variables

[tool.ruff.lint.isort]
force-sort-within-sections = true
known-first-party = ["config", "utils", "app"]
forced-separate = ["tests"]

[tool.ruff.lint.isort.sections]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

[tool.pytest.ini_options]
addopts = "--exitfirst --log-cli-level=INFO"
testpaths = ["app/tests"]
minversion = "8.2.2"
